### ISSUE TITLE
Add link to display ghcjs snapshot contents

### ISSUE THREAD

**Issue by k-bx** [fpco/stackage-content#10]
There are links on main page to browse latest lts and nightly snapshots. Would be great to add one for `ghcjs-*` packages. Thank you!

**Comment by snoyberg** [comment]
I'm not sure what this means. We don't currently have any ghcjs snapshots.

**Comment by k-bx** [comment]
@snoyberg oh really? As per [comment](https://github.com/commercialhaskell/stack/issues/337#issuecomment-131677050) from @mgsloan:

> I've pushed a new implementation which is based on a resolver setting. The resolver looks like ghcjs-0.1.0_ghc-7.10.2. It now uses ghcjs to build the Setup.hs files, and then runs the resulting javascript in node.

I've had an impression there is the resolver somewhere.

**Comment by snoyberg** [comment]
A resolver doesn't mean a snapshot. In this case, you just get GHCJS and
its bout libraries, and have to manually select everything else.

**Comment by k-bx** [comment]
Huge thanks for explanation!
