### ISSUE TITLE
Add ghc-8.2.1 bindist for OpenBSD 6.1

### ISSUE THREAD

**Issue by romanzolotarev** [fpco/stackage-content#27]
The new bindist for OpenBSD 6.1 has been uploaded to https://www.haskell.org/ghc/download_ghc_8_2_1.html#openbsd_61_x86_64

**It works only on OpenBSD 6.1**.

Seems like we need to add support for multiple OpenBSD versions first.

Related: 
- https://ghc.haskell.org/trac/ghc/ticket/14041
- #25 
- https://github.com/commercialhaskell/stack/issues/2822#issuecomment-318883026
- https://github.com/commercialhaskell/stack/pull/3184

**Comment by Blaisorblade** [comment]
On it, thanks for the pointer! BTW, news on https://ghc.haskell.org/trac/ghc/ticket/14044#ticket? Does it affect the bindist Stack already ships? Confused.

**Comment by romanzolotarev** [comment]
@Blaisorblade  https://ghc.haskell.org/trac/ghc/ticket/14044#ticket is still open. I have tried to install GHC 8.2.1
- via Stack 
- and directly from https://downloads.haskell.org/~ghc/8.2.1/ghc-8.2.1-x86_64-openbsd60-openbsd.tar.xz 

Neither of them work on OpenBSD 6.0

**Comment by Blaisorblade** [comment]
Since this issue will be closed soon I opened #28 to keep track.

**Comment by borsboom** [comment]
Given the upstream GHC issue is still open, and they didn't release any OpenBSD bindists for GHC 8.2.2, maybe we should consider GHC support for OpenBSD defunct for now and remove the non-working bindists from stack-setup-2.yaml.

@Blaisorblade @romanzolotarev Any thoughts?
