### ISSUE TITLE
Removing -nopie variants for GHC versions <8.0.2

### ISSUE THREAD

**Issue by enolan** [fpco/stackage-content#35]
In abc87ef7, the `-nopie` variant of GHC for versions prior to 8.0.2 were removed. This breaks builds for any project using those GHC versions on Linux distributions with PIE on by default. From the commit message: "Removes GHC <8.0.2 for all Linux `-nopie` builds, since those don't work reliably." This was on purpose apparently, but I think it was a really bad decision. One of the main purposes of Stack(age) is reliable/reproducible builds - if you have code that built in December it should still build in January regardless of what anybody else does. The `-nopie` variants may not have worked for some people / some distros, but that doesn't mean you should break them for everyone they do work for. I wiped out `~/.stack` today (for unrelated reasons) and all of a sudden I couldn't build my project anymore.

I was able to get around this by setting the `--setup-info-yaml` option to the previous `stack-setup-2.yaml` version.

**Comment by enolan** [comment]
Thanks @borsboom! Any chance of making 7.10.2. work as well? I'm happy to help.

**Comment by borsboom** [comment]
@enolan https://github.com/fpco/stackage-content/pull/37 should have you covered.
