### ISSUE TITLE
`global-hints.yaml` incomplete; omits `Win32`

### ISSUE THREAD

**Issue by mpilgrem** [fpco/stackage-content#45]
`global-hints.yaml` omits certain packages reported by `stack --resolver <ghcVer> exec --no-ghc-package-path -- ghc-pkg list --global --no-user-package-db --simple-output` on Windows 10, because the executable used to update it (at https://github.com/fpco/stackage-content/blob/master/stack/update-global-hints.hs) was run on Linux. Specifically:
- on Windows, the `ghc-pkg list` will include in its output `Win32` (but not `terminfo` or `unix`)
- on Unix-like operating systems, it will include `terminfo` and `unix` (but not `Win32`)

(See: https://github.com/commercialhaskell/stackage/issues/3934#issuecomment-417577744)

I will propose a pull request that manually adds the missing `Win32` packages to date.

**Comment by sgraf812** [comment]
This happens again for `ghc-8.6.3`.

**Comment by mpilgrem** [comment]
I will propose a pull request that manually adds the missing `Win32` packages to date.

**Comment by mpilgrem** [comment]
I've found a pull request already proposed, #57.
