### ISSUE TITLE
Not supporting manually specified compiler versions?

### ISSUE THREAD

**Issue by 3noch** [fpco/stackage-content#5]
It appears that the current MO is to only serve the most recent minor version of GHC. I'm sure this works 99% of the time, but it's possible for folks to manually demand a specific GHC version in their `stack.yaml` file. Is that not truly supported?

**Comment by mgsloan** [comment]
Demanding a specific GHC version is supported, and stackage snapshots now specify an exact ghc version.

setup-info has info for 7.10.1, 7.10.2, and 7.10.3.  I think we just had the most recent minor versions at the release of stack, but we'll keep adding minor version releases as they come out (and not remove the old ones)
